---
- name: Load a variable file based on the OS type.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure Supervisor is installed.
  vars:
    ansible_python_interpreter: >
      {% if ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8" %}
      /usr/bin/python3.6
      {% else %}
      /usr/bin/python3
      {% endif %}
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version | default(omit) }}"

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- include_tasks: config.yml

- include_tasks: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisord
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: true
  when: supervisor_enabled
